name: test.jffai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23504
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#022135'
    - '#f7ffff'
    - '#b5c1bd'
    - '#145575'
    - '#902a1b'
  brandStrength: 0.8125
  lightness: 0.6989247
  saturation: 0.3028674
  rhythmicContrast: 0.7849463
purpose: []
