name: test.jffai
favicon: null
layout_spectrum: 0.6884991612751037
typography_spectrum: 0.5876386088784784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.18041252670809627
  lightness: 0.8577462728135288
  saturation: 0.14346981653943658
  rhythmicContrast: 0.8763084514066577
purpose: []
